Y

diff --git a/library/library/libdisk/101/premak b/library/library/libdisk/101/premak
--- a/library/library/libdisk/101/premak
+++ b/library/library/libdisk/101/premak
@@ -9,20 +9,20 @@ function raptor_disks_init_pure() {
 
 ## dualboot validator team # @Al Muhdil Karim <karim@yuros.org> @Fawaz Rifqi Frasetia <fras@yuros.org>
 function raptor_disks_init_dual() {
+    
+    dualboot=false
+    efipaths=($(lsblk -o path,fstype | grep vfat | awk '{print $1}'))
 
-    take_efipath=($(lsblk -o path,fstype | grep vfat | awk '{print $1}'))
-
-    for item_efipath in "${take_efipath[@]}"; do
+    for item_efipath in "${efipaths[@]}"; do
 
         echo "check efi partition at $item_efipath" 
         sudo mount $item_efipath /srv && sleep 2 && 
-       
-        if [[ -d "/srv/EFI/Microsoft" ]]; then
-            winefipath="$item_efipath" && mkdir -p "$item_efipath/Linux" &&
-            echo "check windows efi partition found at $item_efipath"
-            dualboot=true
-        fi
 
+        if [[ -d "/srv/EFI/Microsoft" ]]; then
+            dualboot=true &&
+            uefipath="$item_efipath" && 
+            echo "windows efi partition : $item_efipath"
+        fi
         sleep 1 && sudo umount -R /srv && sleep 2
 
     done
@@ -30,12 +30,30 @@ function raptor_disks_init_dual() {
 
 function raptor_disks_init_swip() {
 
-    if [[ $dualboot == false ]];then
+    if [[ -n $uefipath ]];then
+        local pathuefi=$( lsblk -o path,label | grep $uefipath )
+    fi
+
+    if [[ -n $rootpath ]];then
+        local pathroot=$( lsblk -o path,label | grep $rootpath )
+    fi
+
+    if [[ -n $swappath ]];then
+        local pathswap=$( lsblk -o path,label | grep $swappath )
+    fi
+
+    if [[ -n $homepath ]];then
+        local pathhome=$( lsblk -o path,label | grep $homepath )
+    fi
+
+    if [[ $dualboot == false ]]&&[[ -z $pathuefi ]]&&[[ -z $pathroot ]]&&[[ -z $pathswap ]]&&[[ -z $pathhome ]];then
 
         read -p "Do yout want swipe partition table : [y/N] " swipe_partition_table
 
         if [[ $swipe_partition_table == "Y" ]]||[[ $swipe_partition_table == "y" ]];then
-            sudo parted -s $drivpath mklabel gpt
+            sudo parted -s $loadpath mklabel gpt
+        else
+            echo "continue installation"
         fi
     fi
 }
@@ -46,66 +64,100 @@ function raptor_disks_init() {
     raptor_disks_init_swip
 }
 
-## MAKE PARTITION
-function raptor_disks_make_boot() {
 
-   if [[ -z $( lsblk -o label | grep "BOOT" ) ]]; then
-        echo "create boot"
-        echo -e "n\np\n\n\n+2G\nt\n\n1\nw" | fdisk "$drivpath" > /dev/null 2>&1
-        sleep 2
-        bootpath=$(lsblk -o path | grep "$drivpath" | tail -n 1)
-        sleep 1
+## MAKE PARTITION
+function raptor_disks_make_uefi() {
+
+    if [[ $dualboot == true ]];then
+        return
+    fi 
+
+    local label=$( lsblk -o label | grep "BOOT" | awk '{print $1}' )
+    local paths=$( lsblk -o path  | grep $uefipath )
+    local sizes=$distro_uefisize
+
+    echo "prepare uefi partition"
+
+    if [[ -z $label ]]&&[[ -z $paths ]]; then
+        echo -e "n\np\n\n\n+$sizes\nt\n\n1\nw" | fdisk "$loadpath" > /dev/null 2>&1 && sleep 2
+        uefipath=$(lsblk -o path | grep "$loadpath" | tail -n 1) && sleep 1
+    elif [[ -n $paths ]];then
+        uefipath=$paths
+    elif [[ -n $label ]];then
+        uefipath=$label
     else
-        echo "prepare boot"
-        bootpath=$(lsblk -o path,label | grep "BOOT" | awk '{print $1}')
+        echo "error uefi partition not found"
+        exit 1
     fi
 }
 
 function raptor_disks_make_root() {
     
-    if [[ -z $( lsblk -o label | grep "ROOT" ) ]]; then
-        echo "create root"
-        echo -e "n\np\n\n\n+27G\nw" | fdisk "$drivpath" > /dev/null 2>&1
-        sleep 2
-        rootpath=$(lsblk -o path | grep "$drivpath" | tail -n 1)
-        sleep 1
+    local label=$( lsblk -o label | grep "ROOT" | awk '{print $1}' )
+    local paths=$( lsblk -o path | grep $rootpath )
+    local sizes=$distro_procsize
+
+    echo "create root partition"
+    if [[ -z $label ]]&&[[ -z $paths ]]; then
+        echo -e "n\np\n\n\n+$sizes\nw" | fdisk "$loadpath" > /dev/null 2>&1 && sleep 2
+        rootpath=$(lsblk -o path | grep "$loadpath" | tail -n 1) && sleep 1
+    elif [[ -n $paths ]];then
+        rootpath=$paths
+    elif [[ -n $label ]];then
+        rootpath=$label
     else
-        echo "prepare root"
-        rootpath=$(lsblk -o path,label | grep "ROOT" | awk '{print $1}')
+        echo "error root partition not found"
+        exit 1
     fi
 }
 
 function raptor_disks_make_swap() {
-    
-    if [[ -z $( lsblk -o path,fstype | grep "swap" ) ]]; then
-        echo "create swap"
-        echo -e "n\np\n\n\n+4G\nw" | fdisk "$drivpath" > /dev/null 2>&1
-        sleep 2
-        swappath=$(lsblk -o path | grep "$drivpath" | tail -n 1)
-        sleep 1
+
+    local label=$( lsblk -o label | grep "swap" | awk '{print $1}' )
+    local paths=$( lsblk -o path | grep $swappath )
+    local sizes=$distro_swapsize
+
+    echo "create swap partition"
+
+    if [[ -z $label ]]&&[[ -z $paths ]]; then
+        echo -e "n\np\n\n\n+$sizes\nw" | fdisk "$loadpath" > /dev/null 2>&1 && sleep 2
+        swappath=$(lsblk -o path | grep "$loadpath" | tail -n 1) && sleep 1
+    elif [[ -n $paths ]];then
+        swappath=$paths
+    elif [[ -n $label ]];then
+        swappath=$label
     else
-        echo "prepare swap"
-        swappath=$(lsblk -o path,fstype | grep swap | awk '{print $1}' )
+        echo "error swap partition not found"
+        exit 1
     fi
 }
 
 function raptor_disks_make_home() {
-    
-    if [[ -z $( lsblk -o label | grep "HOME" ) ]]; then
-        echo "create home"
-        echo -e "n\np\n\n\n\nw" | fdisk "$drivpath" > /dev/null 2>&1
-        sleep 2
-        homepath=$(lsblk -o path | grep "$drivpath" | tail -n 1 )
-        sleep 1
+
+    local label=$( lsblk -o label | grep "HOME" | awk '{print $1}' )
+    local paths=$( lsblk -o path | grep $homepath )
+    local sizes=$distro_homesize
+
+    echo "create home partition"
+    if [[ -z $label ]]&&[[ -z $paths ]]&&[[ $sizes == "all" ]]; then
+        echo -e "n\np\n\n\n\nw" | fdisk "$loadpath" > /dev/null 2>&1 && sleep 2
+        homepath=$(lsblk -o path | grep "$loadpath" | tail -n 1) && sleep 1
+    elif [[ -z $label ]]&&[[ -z $paths ]]&&[[ $sizes != "all" ]]; then
+        echo -e "n\np\n\n\n+$sizes\nw" | fdisk "$loadpath" > /dev/null 2>&1 && sleep 2
+        homepath=$(lsblk -o path | grep "$loadpath" | tail -n 1) && sleep 1
+    elif [[ -n $paths ]];then
+        homepath=$paths
+    elif [[ -n $label ]];then
+        homepath=$label
     else
-        echo "prepare home"
-        homepath=$(lsblk -o path,label | grep "HOME" | awk '{print $1}')
+        echo "error home partition not found"
+        exit 1
     fi
 }
 
 function raptor_disks_make() {
     echo "starting auto partitioning"
-    raptor_disks_make_boot &&
+    raptor_disks_make_uefi &&
     raptor_disks_make_root &&
     raptor_disks_make_swap &&
     raptor_disks_make_home
@@ -117,7 +169,7 @@ function raptor_disks_prev() {
     clear &&
     echo "Storage Information preview"
     echo "--------------------------------"
-    echo "boot path : $bootpath"
+    echo "boot path : $uefipath"
     echo "root path : $rootpath"
     echo "swap path : $swappath"
     echo "home path : $homepath"
@@ -131,9 +183,13 @@ function raptor_disks_prev() {
 } 
 
 ## FORM PARTITION
-function raptor_disks_form_boot() {
-    echo "format boot partition"
-    mkfs.vfat -F32 -S 4096 -n "BOOT" $bootpath
+function raptor_disks_form_uefi() {
+
+    echo " duaboot status : "$dualboot
+    if [[ $dualboot == false ]];then
+        echo "format boot partition"
+        mkfs.vfat -F32 -S 4096 -n "BOOT" $uefipath
+    fi
 }
 
 function raptor_disks_form_root() {
@@ -142,8 +198,10 @@ function raptor_disks_form_root() {
 }
 
 function raptor_disks_form_swap() {
-    echo "format swap partition"
-    mkswap $swappath
+    if [[ -n $swappath ]];then
+        echo "format swap partition"
+        mkswap $swappath
+    fi
 }
 
 function raptor_disks_form_home() {
@@ -154,9 +212,9 @@ function raptor_disks_form_home() {
 }
 
 function raptor_disks_form() {
-    raptor_disks_form_boot
-    raptor_disks_form_root
-    raptor_disks_form_swap
+    raptor_disks_form_uefi &&
+    raptor_disks_form_root &&
+    raptor_disks_form_swap &&
     raptor_disks_form_home
 }
 
@@ -167,16 +225,17 @@ function raptor_disks_mont_root() {
     mkdir -p /mnt/{home,boot}
 }
 
-function raptor_disks_mont_boot() {
-    mount -o uid=0,gid=0,dmask=007,fmask=007 $bootpath /mnt/boot
-    mkdir -p /mnt/boot/{efi,kernel,loader}
-    mkdir -p /mnt/boot/efi/{boot,linux,systemd}
+function raptor_disks_mont_uefi() {
 
-}
-
-function raptor_disks_mont_swap() {
-    echo "mount swap partition"
-    swapon $swappath
+    if [[ $dualboot == true ]];then
+        mkdir -p /mnt/boot/{efi,kernel}
+        mount -o uid=0,gid=0,dmask=007,fmask=007 $uefipath /mnt/boot/efi
+        mkdir -p /mnt/boot/efi/EFI/{linux,systemd}
+    else
+        mount -o uid=0,gid=0,dmask=007,fmask=007 $uefipath /mnt/boot
+        mkdir -p /mnt/boot/{efi,kernel,loader}
+        mkdir -p /mnt/boot/efi/{boot,linux,systemd}
+    fi
 }
 
 function raptor_disks_mont_home() {
@@ -184,20 +243,24 @@ function raptor_disks_mont_home() {
     mount $homepath /mnt/home
 }
 
+function raptor_disks_mont_swap() {
+    echo "mount swap partition"
+    swapon $swappath
+}
+
 function raptor_disks_mont() {
     raptor_disks_mont_root &&
-    raptor_disks_mont_boot &&
-    raptor_disks_mont_swap &&
-    raptor_disks_mont_home
+    raptor_disks_mont_uefi &&
+    raptor_disks_mont_home &&
+    raptor_disks_mont_swap
 }
 
 function raptor_disks_prep() {
-
     clear && echo "Partition configuration"
     raptor_disks_init &&
     raptor_disks_make &&
     raptor_disks_prev &&
     raptor_disks_form &&
     raptor_disks_mont &&
-    echo "configration done"
+     echo "configration done"
 }
